name: Deploy

on:
  push:
    branches:
    - "*"  # run for branches
jobs:
  deploy:
    name: all
    runs-on: ubuntu-latest
    steps:
      - name: chekcout
        uses: actions/checkout@v2
        
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: setup just 
        uses: extractions/setup-just@v1
        
      - name: export client cert ssh-key
        env: 
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          TENANT_ID: ${{secrets.TENANT_ID}}
        run: |
          pwd
          cat << EOF > ~/work/az-vms/az-vms/terraform.tfvars
          client_id=$CLIENT_ID
          subscription_id=$SUBSCRIPTION_ID
          client_secret=$CLIENT_SECRET
          tenant_id=$TENANT_ID
          EOF

      - name: echo pub ssh-key
        run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa.pub
          echo ${{secrets.SSH-KEY}} > ~/.ssh/id_rsa.pub
          pwd && ls

      - name: Init
        run: just init
        
      - name: Plan
        run: just plan
      
      - name: Apply 
        run: just apply
         


