name: Deploy

on:
  push:
    branches:
    - "*"  # run for branches


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
        
      - name: chekcout
        uses: actions/checkout@v2
  
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: setup just 
        uses: extractions/setup-just@v1

      - name: install az cli   
        run:  pip install azure-cli

      - name: export client cert ssh-key
        run: |
          cat << EOF > ~/pass.pem
          ${{secrets.PASSWORD}}
          EOF
      


      - name: login
        env:
          APP_ID: ${{ secrets.APP_ID }}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{ secrets.PASSWORD }}
          TENANT_ID: ${{secrets.TENANT_ID}}
        run: az login --service-principal --username $APP_ID --p ~/pass.pem --tenant $TENANT_ID
        
         
      - name: Init
        run: just init
        
      - name: Plan
        run: just plan
      
      - name: Apply 
        run: just apply
         


